# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ashita
  password: 

development:
  <<: *default
  database: notebook_dev

test:
  <<: *default
  database: noteboot_test

production:
  <<: *default
  database: db/production.sqlite3
