# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'ScoreApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScoreApp
  pod 'KituraKit', :git => 'https://github.com/IBM-Swift/KituraKit.git', :branch => 'pod'

  target 'ScoreAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScoreAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
